version: '3.4'

services:
  forgebase.identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - MasterdataUrl=http://${FORGEBASE_EXTERNAL_DNS_NAME_OR_IP}:39522
      - TZ=Asia/Kolkata
    ports:
      - "5000:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - "/etc/localtime:/etc/localtime:ro"
  forgebase.masterdata:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - identityUrl=http://forgebase.identity
      - ExternalIdentityUrl=http://${FORGEBASE_EXTERNAL_DNS_NAME_OR_IP}:5000
      - TZ=Asia/Kolkata
    ports:
      - "5002:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - "/etc/localtime:/etc/localtime:ro"
